[tool.poetry]
name = "beautysh"
version = "6.0.1"
description = "A Bash beautifier for the masses."
authors = ["Bernardo Meurer <bernardo@meurer.org>"]
license = "MIT"

[tool.poetry.scripts]
beautysh = "beautysh:main"

[tool.poetry.dependencies]
python = "^3.6.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
black = "^21.4b2"
isort = "^5.8.0"
flakehell = "^0.9.0"
pre-commit = "^2.12.1"
python-semantic-release = "^7.15.4"

[tool.pytest.ini_options]
addopts = "-v -Wdefault"

[tool.black]
line-length = 99

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 99

[tool.flakehell]
exclude = ["build"]
max_line_length = 99
# c.f. https://github.com/flakehell/flakehell/issues/10
extended_default_ignore=[ ]

[tool.flakehell.plugins]
mccabe = ["+*"]
pycodestyle = ["+*", "-W503"]
pyflakes = ["+*"]
pylint = ["+*"]

[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
build_command = "make build"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
