name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes recursive-nix
      - uses: cachix/cachix-action@v10
        with:
          name: bernardo
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: lint
        run: cachix watch-exec bernardo -- nix develop -c make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes recursive-nix
      - uses: cachix/cachix-action@v10
        with:
          name: bernardo
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: test
        run: cachix watch-exec bernardo -- nix develop -c make test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes recursive-nix
      - uses: cachix/cachix-action@v10
        with:
          name: bernardo
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: build
        run: cachix watch-exec bernardo -- nix develop -c make build
      - name: nix build
        run: cachix watch-exec bernardo -- nix build -L
